services:
  mongodb:
    image: mongo:latest
    tty: true
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: smoot-admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data
  lavalink:
    image: fredboat/lavalink
    volumes:
      - ./src/application.yml:/opt/Lavalink/application.yml
    expose: ["2333"]
    tty:
      true
  discordbot:
    image: python:3.9
    tty: true
    volumes:
      - ./src:/home/src
    environment:
      DISCORD_SECRET: secret
      BOT_PREFIX: !
      MONGO_PASSWORD: password
      MONGO_USER: smoot-admin
    command: >
      bash -c '
        apt update -y && \
        apt install -y vim && \
        python3 -m venv /home/src/venv/ && \
        python3 -m pip install --upgrade pip && \
        source /home/src/venv/bin/activate && \
        pip install -r /home/src/requirements.txt && \
        python -u /home/src/main.py
        '
volumes:
  mongo_data:
