services:
  mongodb:
    image: mongo:latest
    tty: true
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: smoot-admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data
  lavalink:
    image: fredboat/lavalink
    volumes:
      - ./src/application.yml:/opt/Lavalink/application.yml
    expose: ["2333"]
    tty:
      true
  discordbot:
    image: python:3.9
    tty: true
    volumes:
      - ./src:/home/src
    environment:
      DISCORD_SECRET: "MTEyNTgzMjU3NDU2OTI5OTk3OA.Gejh0-.jAvykyPHp_U-dpy4lHw9fIC_xecPkMXsX2H8u8"
      BOT_PREFIX: "!"
      MONGO_PASSWORD: password
      MONGO_USER: smoot-admin
    command: >
      bash -c '
        set -e; \
        apt update -y && \
        apt install -y vim wget curl python3 && \
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && \
        unzip -o ngrok-stable-linux-amd64.zip && \
        ./ngrok http 5000 > /home/src/ngrok.log 2>&1 & \
        sleep 20 && \
        ps aux | grep ngrok && \
        curl --silent http://localhost:4040/api/tunnels || echo "Failed to connect to ngrok" && \
        python3 -m venv /home/src/venv/ && \
        python3 -m pip install --upgrade pip && \
        source /home/src/venv/bin/activate && \
        pip install -r /home/src/requirements.txt && \
        python -u /home/src/main.py
      '







volumes:
  mongo_data:
